remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
description: <p>Professional Website & Data Science Portfolio</p><p><a href="index.html" class="btn">Home</a><a href="research-skills.html" class="btn">Research Skills</a><a href="technical-skills.html" class="btn">Technical Skills</a><a href="https://github.com/calebclayreagor/DELAY" class="btn">DELAY</a></p>
