theme: jekyll-theme-minimal
title: Caleb C. Reagor, PhD
description: <a href="https://adameykolab.eu/authors/creagor/">adameyko lab</a> postdoc<br>caleb dot reagor at ki dot se<br><br><a href=#about-me>About me</a><br><a href=#publications>Publications</a><br><a href=#curriculum-vitae>Curriculum vitae</a>
logo: /images/CalebReagor.jpg
