theme: jekyll-theme-minimal
title: Caleb Clay Reagor
description: phd student part of <a href="https://compbio.triiprograms.org">tri-i cbm</a>
logo: /images/CalebReagor.jpg
heading_anchors: true

# navigation bar
nav:
- page: About Me
  permalink: #about-me
