remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
description:
<p>
  <a href="index.html" class="btn">Summary</a>
  <a href="research-skills.html" class="btn">Research Skills</a>
</p>
